### ISSUE TITLE
Is it possible to use this and Snapguidist together?

### ISSUE THREAD

**Issue by iamtyce** [trabe/styleguidist-goodies#4]
I'd really like to use this add-on (particularly for navigation issues!) but we currently wrap the config in a Snapguidist reference:

```jsx
const snapguidist = require('snapguidist');
module.exports = snapguidist({})
```
Do you know if it's possible to use both together?

**Comment by davidbarral** [comment]
Never tried. If snapguidist generates an standard styleguidist config it should be possible because styleguidist-goodies honors the styleguidist config params. 

Have you tried something like this?:

```
const snapguidist = require('snapguidist');
const { guideConfig } = require("styleguidist-goodies");

module.exports = guideConfig(Object.assign({
   // styleguidist-goodies specific config entries here :)
}, snapguidist({})));
```

**Comment by iamtyce** [comment]
Trying to get this running even without the above modification for Snapguidist keeps returning this:

`Unknown config option src with value ""../components/**/*.js"" was found.`

I've verified that `styleguidist-goodies` is definitely installed in `node_modules` but it seems like RSG doesn't realise it's there?

**Comment by davidbarral** [comment]
Hello. 

We will soon release a v3.0.0 version compatible with Styleguidist 6.x. The new version will just provide utility functions instead of a config builder. Using this approach it should be possible to use this lib with others like snapguidist.

We do not plan to add more features to the 2.x branch. 

Regards.

**Comment by iamtyce** [comment]
Sounds great, thanks @davidbarral! Looking forward to `v3` 😄
